model_list:
  - model_name: gpt-5
    litellm_params:
      model: openai/gpt-5
      api_key: ${OPENAI_API_KEY}
# Examples of other providers/models you can add later:
# - model_name: claude-3-7-sonnet
# litellm_params:
# model: anthropic/claude-3-7-sonnet
# api_key: ${ANTHROPIC_API_KEY}
# - model_name: google-gemini-2.0-flash
# litellm_params:
# model: google/gemini-2.0-flash
# api_key: ${GOOGLE_API_KEY}
# - model_name: llama3.1:8b
# litellm_params:
# model: ollama/llama3.1:8b
# api_base: http://ollama:11434
litellm_settings:
  telemetry: false
  drop_params: true
  general_settings:
    master_key: "somesupermasterkey"

router_settings:
  num_retries: 2
# Optional request logging to a lightweight SQLite file
proxy_logging:
  log_file: /data/litellm_proxy.db
  redact_user_info: true
