services:
  kasm:
    image: lscr.io/linuxserver/kasm:git-5d8820f
    container_name: kasm
    privileged: true
    security_opt:
      - apparmor:rootlesskit #optional
    environment:
      - KASM_PORT=443
      - DOCKER_HUB_USERNAME=${USER} #optional
      - DOCKER_HUB_PASSWORD=${PASS} #optional
      - DOCKER_MTU=1500 #optional
    volumes:
      - ${DATA}:/opt
      - ${PROFILES}:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
