---
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - OIDC_PROVIDER_METADATA_URL=${OIDC_PROVIDER_METADATA_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_CLIENT_CRYPTO_KEY=${OIDC_CLIENT_CRYPTO_KEY}
      - OIDC_ENABLED=1
      - OIDC_X_FORWARDED_HEADERS="X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto"
      - OIDC_SCOPES="openid email profile"
      - OIDC_REMOTE_USER_CLAIM=preferred_username
      - TRUSTED_PROXY="172.25.0.0/24"
    volumes:
      - ${config}:/config
    #ports:
     # - 80:80 not needed -> only proxy access
    restart: unless-stopped

    networks:
      - proxy-net
networks:
  proxy-net:
    external:
      name: proxy-net
